/// URLs for offline cache.
final List<String> offlineUrls = [
  './.last_build_id',
  './cache.dill.track.dill',
  './e718c584ce5f0c71ff76227d45ee3982/gen_localizations.stamp',
  './f872507f30e2ff2523f0f1d19160266e.cache.dill.track.dill',
  './flutter_assets/AssetManifest.json',
  './flutter_assets/FontManifest.json',
  './flutter_assets/NOTICES',
  './flutter_assets/fonts/MaterialIcons-Regular.otf',
  './flutter_assets/kernel_blob.bin',
  './flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf',
  './flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-brands-400.ttf',
  './flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-regular-400.ttf',
  './flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf',
  './web/',
  './web/.last_build_id',
  './web/assets/AssetManifest.json',
  './web/assets/FontManifest.json',
  './web/assets/NOTICES',
  './web/assets/fonts/MaterialIcons-Regular.otf',
  './web/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf',
  './web/assets/packages/font_awesome_flutter/lib/fonts/fa-brands-400.ttf',
  './web/assets/packages/font_awesome_flutter/lib/fonts/fa-regular-400.ttf',
  './web/assets/packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf',
  './web/favicon.png',
  './web/flutter_service_worker.js',
  './web/icon/128.png',
  './web/icon/144.png',
  './web/icon/152.png',
  './web/icon/192.png',
  './web/icon/384.png',
  './web/icon/512.png',
  './web/icon/72.png',
  './web/icon/96.png',
  './web/main.dart.js',
  './web/main.dart.js.map',
  './web/manifest.json',
  './web/pwa.dart',
  './web/version.json',
];

/// Last modified timestamp of the files
final String lastModified = '2020-10-06T21:57:39.000Z';
